[package]
name = "yummy-metadata-derive"
version = "0.1.0"
authors = ["Daniel Mason <daniel@danielmason.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.36"
quote = "0.6.12"
