[package]
name = "yummy-metadata-test"
version = "0.1.0"
authors = ["Daniel Mason <daniel.mason@apolitical.co>"]
edition = "2018"

[dependencies]
yummy-metadata = { path = "../yummy-metadata" }
yummy-metadata-derive = { path = "../yummy-metadata-derive" }